### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by adrtarnowski** [datacontract/datacontract-specification#53]
Hi, 

I've got the following error when I run the _test_ command:

```shell
HTTPSConnectionPool(host='datacontract.com', port=443): Max retries exceeded with url: /datacontract.schema.json
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to
get local issuer certificate (_ssl.c:1000)')))
```
Could you help with that?

![image](https://github.com/datacontract/datacontract-specification/assets/8177306/210db143-278c-43e1-8cc8-f02d206ca811)

**Comment by jochenchrist** [comment]
[adrtarnowski](https://github.com/adrtarnowski) thanks for reporting.

I struggle to reproduce this issue, can you provide some details about your runtime environment (OS, CLI Python version, Docker, ...)?

**Comment by adrtarnowski** [comment]
Python: 3.12.2

Full Exception message:
ERROR:root:Exception occurred
Traceback (most recent call last):
  File "C:\Users\adrian.tarnowski\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "C:\Users\adrian.tarnowski\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "C:\Users\adrian.tarnowski\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adrian.tarnowski\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\adrian.tarnowski\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adrian.tarnowski\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adrian.tarnowski\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adrian.tarnowski\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1042, in _create
    self.do_handshake()
  File "C:\Users\adrian.tarnowski\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

I use Windows local CLI (the same issue with my docker), but I think it's my local issue. I tried to fix it by using that command
pip install --upgrade certifi but with no success. Could you advice how to solve it?

**Comment by adrtarnowski** [comment]
I found a solution for people who like Windows ;)
`pip install pip-system-certs`
and it works. Thank you for that you checked the certificate from your side, and everything is ok with it :)

**Comment by adrtarnowski** [comment]
pip install --upgrade certifi
and
pip install pip-system-certs

commands will be your friends if you face the similar issue

**Comment by jochenchrist** [comment]
Thanks, @adrtarnowski, for finding the solution!
